### ISSUE TITLE
which  Visual Studio version you used? 

### ISSUE THREAD

**Issue by waterfoxfox** [lelegard/srt-win-installer#2]
Thanks for your great project,  i have download your static lib ,  link error happens in visual studio 2015

**Comment by lelegard** [comment]
Hi,

For the releases of this project, I always use the latest version of VS, currently VS 2019 v16.4.x.

If you need a build for another version, just clone the srt-win-installer repo and execute the PowerShell script `build-all.ps1`.

**Comment by waterfoxfox** [comment]
thanks for your reply!
