### ISSUE TITLE
can not find cmake

### ISSUE THREAD

**Issue by waterfoxfox** [lelegard/srt-win-installer#3]
build-srt.ps1  Line:150  should add cmake path?  like this:  

  $MSRoots = @("C:\Program Files*\MSBuild", "C:\Program Files*\Microsoft Visual Studio", "C:\Program Files*\CMake\bin")

**Comment by lelegard** [comment]
Cmake is installed with Visual Studio, but the option must be checked. See the last line from this:

![image](https://user-images.githubusercontent.com/5641922/75329980-e2a8e880-5880-11ea-9591-fc85de529f1b.png)

Then, `cmake.exe` is somewhere under various VS installations, possibly several times. The following instruction from `build-srt.ps1` selects the `cmake.exe`  with the highest version:
~~~
$CMake = Get-ChildItem -Recurse -Path $MSRoots -Include cmake.exe -ErrorAction Ignore |
    ForEach-Object { (Get-Command $_).FileVersionInfo } |
    Sort-Object -Unique -Property FileVersion |
    ForEach-Object { $_.FileName} |
    Select-Object -Last 1
~~~

Launch "Visual Studio Installer" from the start menu, then select "Modify" and make sure that "CMake tools" are selected in your VS installation. This works exactly like this with VS2019. Maybe some menus are different with other versions but the idea is the same.

**Comment by waterfoxfox** [comment]
thanks for your reply, i use visual studio 2015, cmake is not optional for its installation,  so i download from cmake org web, and install independent
